### PR TITLE
Remove deterministic ar and ranlib wrappers.

### PR DESCRIPTION
**Pull request by benjaminp**
Instead, use the --enable-deterministic-ar binutils configure option.

### CODE REVIEW

**Comment by nicolov** [comment]
@benjaminp Are you still using this with Bazel?

**Comment by benjaminp** [comment]
sort of. I use a forked version of this script with additional simplifications and compatibility fixes for newer toolchain components. This PR was a feeler to see if anything would be accepted.

**Comment by nicolov** [comment]
Cool. Did you find it better than just having a gentoo chroot and pointing the compiler there?

**Comment by benjaminp** [comment]
I didn't try anything like that, so hard to say. :) A chroot isn't really exactly what you want anyway, since ultimately you want glibc compiled with a --prefix not equal to /usr.

**Comment by nicolov** [comment]
Correct. One can get pretty far with a generous sprinkle of RPATHs, but ultimately glibc gets you.

Gentoo has [Gentoo prefix](https://wiki.gentoo.org/wiki/Project:Prefix/Technical_Documentation) that people install alongside their main system, and it bootstraps the distribution from source. I was thinking that it would be useful to be able to build some packages from source that you don't want to bother porting to bazel.

**Comment by benjaminp** [comment]
Maybe, but I've "just" written Bazel rules for everything but glibc.

One thing lrte/grte/crosstool devote a lot of effort to, which I'm not sure Gentoo prefix does, is reproducibility. In theory, it should be possible to obtain the same outputs from LRTE on any sort of Linux system with a C compiler. These scripts are not trivial by any means but are certainly more self-contained than the Gentoo package-management tools.

**Comment by mzhaom** [comment]
Thank you @benjaminp. Sorry it took some years to see the PR, :)

**Comment by benjaminp** [comment]
Thanks for the merge.

**Pull request merged**
